### ISSUE TITLE
Doesn't work BlockLogger

### ISSUE THREAD

**Issue by ghost** [LilCrispy2o9/BlockLogger#2]
![default](https://cloud.githubusercontent.com/assets/5405019/6322604/6ca4d79c-bb5b-11e4-9d4d-40253745feef.PNG)
Apply it and reboot the server, and I break grass block.

![default](https://cloud.githubusercontent.com/assets/5405019/6322621/cf804ac2-bb5b-11e4-93fb-ec213cad401d.PNG)

Doesn't work...

OS : CentOS 6 64bit
Version : PocketMine-MP 1.4.1dev

**Comment by truelinux** [comment]
May i see your config please?

**Comment by ghost** [comment]
@LilCrispy2o9 
![default](https://cloud.githubusercontent.com/assets/5405019/6323004/b958de72-bb64-11e4-900e-6c29c0793390.PNG)

**Comment by ghost** [comment]
@LilCrispy2o9 
![default](https://cloud.githubusercontent.com/assets/5405019/6323035/5e751740-bb65-11e4-938e-1a94f727d8be.PNG)
.. And Running Windows 8

**Comment by truelinux** [comment]
1. You must replace "Crispeh" with the name of the player you want to log.
2. To fix that error, delete the BlockLogger folder and restart
