### ISSUE TITLE
Add automatic player log?

### ISSUE THREAD

**Issue by matcracker** [LilCrispy2o9/BlockLogger#3]
Can you add an automatic system of log player when they joined?

**Comment by McDrakon123** [comment]
I am making a version of this plugin where it will log all players and the world as well as a command that should let you see the data on the block you are standing on. When i have it working i will fork it on github. The world support already works and also does searching using XYZ coords. The only issue is trying to send the data to the player who sent the command. The XYZ search only works when using console atm.

**Comment by DevScyu** [comment]
I have a version of this plugin with working world support, search data using the location you are standing on in-game, delete data from _x_ days ago on startup, customize what blocks get logged, logs all players by default, can disable logging for certain players, highly customizable.
